PACKAGE_NAME="ov02c10-patched"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="ov02c10"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
MAKE[0]="make KERNELRELEASE=${kernelver} KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"
REMAKE_INITRD="no"
